<?php

/**
 * @file d8_training module file.
 */
use Drupal\d8_training\Event\NodeInsertEvent;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme()
 */
function d8_training_theme() {
  return [
    'weather_info_block' => [
      'variables' => [
        'temp' => NULL,
        'city' => NULL,
        'pressure' => NULL,
        'humidity' => NULL,
        'temp_min' => NULL,
        'temp_max' => NULL,
        'wind_speed' => NULL,
      ],
      'template' => 'block-weather-info',
    ],
  ];
}

  /**
   * @param \Drupal\node\NodeInterface $node
   */
  function d8_training_node_insert(NodeInterface $node) {
    // Dispatch the node insert event so that subscribers can act accordingly.
     \Drupal::service('event_dispatcher')->dispatch(NodeInsertEvent::NODE_INSERT, new NodeInsertEvent($node));
  }

